// @ts-check
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Repository variables `SITE_URL` and `SITE_BASE` are set in CI (see CONTRIBUTING.md).
// The custom domain, once it exists, will set SITE_BASE=/ (and SITE_URL to the domain)
// without a code change.
const site = process.env.SITE_URL ?? 'https://tabula-cms.github.io';
const base = process.env.SITE_BASE ?? '/site';

const docsDir = fileURLToPath(new URL('./src/content/docs/', import.meta.url));

// The four documentation groups below are generated by `scripts/fetch-docs.mjs` (issue #3)
// into gitignored folders. Each group is only added to the sidebar once its folder has
// actually been imported — otherwise the group would show with no pages under it (an
// autogenerated group with a missing directory still builds, it's just empty and useless).
/** @type {{ label: string; directory: string }[]} */
const docGroups = [
	{ label: 'Посібник редактора', directory: 'editor' },
	{ label: 'Встановлення', directory: 'install' },
	{ label: 'Тестування', directory: 'qa' },
	{ label: 'Для розробників', directory: 'dev' },
];

const sidebar = docGroups
	.filter(({ directory }) => existsSync(`${docsDir}${directory}`))
	// NOTE: not the `{ label, autogenerate }` shorthand — @astrojs/starlight 0.42.4 removed
	// support for that form ("Support for autogenerated sidebar groups was removed in
	// Starlight v0.39.0") and errors on it. This `items: [{ autogenerate }]` form is what
	// its own error message recommends.
	.map(({ label, directory }) => ({ label, items: [{ autogenerate: { directory } }] }));

// https://astro.build/config
export default defineConfig({
	site,
	base,
	integrations: [
		starlight({
			title: 'Tabula',
			// Single locale: the site is Ukrainian. Developer docs (/dev/) are English; their
			// <html lang> comes from a per-page `lang` frontmatter field via src/routeData.ts
			// (Starlight's own locale routing can't do this without an /en/ tree — see
			// CLAUDE.md). No /en/ tree, no locale switcher.
			locales: {
				root: { label: 'Українська', lang: 'uk' },
			},
			routeMiddleware: './src/routeData.ts',
			// Imported pages have no meaningful git history in this repository. "Edit this page"
			// links are set per page by the import script (#3) as an absolute editUrl pointing
			// at tabula-cms/tabula; there is no site-wide editLink.baseUrl (see CLAUDE.md).
			lastUpdated: false,
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/tabula-cms/tabula' }],
			sidebar,
		}),
	],
});
